# .github/workflows/rosti_deploy.yml

name: Deploy into Roští.cz

on:
    push:
      branches: [main]

jobs:
    deploy:
      runs-on: ubuntu-latest
      env:
        HOST: ssh.rosti.cz
        USER: app
        PORT: 10743
        NODE_VERSION: 24.4.1
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "v24.4.1"
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.ROSTI_DEPLOY_SSH_KEY }}
      - name: Setup hostkey
        run: |
          echo "ssh.rosti.cz ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUY4mfza2Qivz8WWyzCEmOzHy+82Ssw83/qKHpPtUC6bX6mVB5243B8xGWrYZNBVfzr0I4eEc4Mw5iEyGFdW9xfxQBaa45slmqELsgDEoNJYNFiu56VybcTN+7UJkSuGQIptohuLEHLLLfU+nWFHta334wXXRaukfxNqRkamhKJttCv/PRhR7I3jhJz+O4OECemfa7Pj7na87GwAs6Iv+6HZM+HCp86CWOSf4V4OPja77zcJI7gChJLArL30KON2NEYXF7ashczGFmKLb9bpingvfgOwIUPfrja88fQyN1/I3LRaSqXNJAFDdv6MoWmoJLwyXrGA28JayaG9+kCQ5Z" > ./known_hosts
      - name: env
        run: |
          cat << EOF > .env
          ${{ secrets.ENV }}
          EOF
      - name: Dependencies
        run: |
          npm install
      - name: Build
        run: |
          npm run build
      - name: Setup Node.js
        run: |
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST /usr/local/bin/rosti node $NODE_VERSION
      - name: Setup Supervisord
        run: |
          cat << EOF > rosti.app.conf
          [program:app]
          command=/srv/bin/primary_tech/npm start
          environment=PATH="/srv/bin/primary_tech:/usr/local/bin:/usr/bin:/bin:/srv/.npm-packages/bin"
          stopasgroup=true
          directory=/srv/app
          process_name=app
          autostart=true
          autorestart=true
          stdout_logfile=/srv/log/node.log
          stdout_logfile_maxbytes=2MB
          stdout_logfile_backups=5
          stdout_capture_maxbytes=2MB
          stdout_events_enabled=false
          redirect_stderr=true
          EOF
          scp -o UserKnownHostsFile=./known_hosts -P $PORT rosti.app.conf $USER@$HOST:/srv/conf/supervisor.d/app.conf
          rm rosti.app.conf
      - name: Setup Nginx
        run: |
          cat << EOF > rosti.nginx.conf
          server {
              listen       0.0.0.0:8000;
              listen       [::]:8000;
              location / {
                      proxy_pass         http://127.0.0.1:8080/;
                      proxy_redirect     default;
                      proxy_set_header   X-Real-IP  \$remote_addr;
                      proxy_set_header   Host       \$host;
              }
              location /static/ {
                      alias /srv/app/public/;
              }
          }        
          EOF
          scp -o UserKnownHostsFile=./known_hosts -P $PORT rosti.nginx.conf $USER@$HOST:/srv/conf/nginx.d/app.conf
          rm rosti.nginx.conf
      - name: Copy code
        run: |
          rsync -ae "ssh -o UserKnownHostsFile=./known_hosts -p $PORT" --delete-after --exclude=.git --exclude=node_modules ./ $USER@$HOST:/srv/app/
      - name: Apply changes
        run: |
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl reread
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST "cd /srv/app && /srv/bin/primary_tech/npm ci --omit=dev"
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl restart app
          ssh -o UserKnownHostsFile=./known_hosts -p $PORT $USER@$HOST supervisorctl restart nginx